= Rocket Chip Generator

This repository contains the Rocket chip generator necessary to instantiate
the RISC-V Rocket Core. For more information on Rocket Chip, please consult our
http://www.eecs.berkeley.edu/Pubs/TechRpts/2016/EECS-2016-17.html[technical report].

== Dependencies

This repository uses version 0.10.1 of https://github.com/sifive/wit[Wit] and version 0.15.1 of https://github.com/sifive/wake[Wake].
Please see the respective repositories and their releases to install these dependencies.

== Checkout The Code

This repository uses https://github.com/sifive/wit[Wit] for dependency fetching and resolution.
Please see the https://github.com/sifive/wit/blob/v0.10.1/share/doc/wit/tutorial.md[Wit tutorial] for more information.

----
$ wit init workspace -a git@github.com:chipsalliance/rocket-chip.git
----

This will clone rocket-chip as well as resolve and fetch all dependencies.

== Compile Rocket Chip

It is not necessary to compile separately from invocation, but it might be useful to understand how the different pieces work.

This repository uses https://github.com/sifive/wake[Wake] for orchestrating the build.
We strongly recommend checking out the https://github.com/sifive/wake/blob/v0.15.1/share/doc/wake/tutorial.md[Wake tutorial].
You can find the Rocket Chip Wake rules in `build.wake` within this repository.

The Rocket Chip Scala code is compiled using https://github.com/sifive/api-scala-sifive[API Scala SiFive],
and can thus be compiled with:

----
$ wake compileScalaModule rocketchipScalaModule
----

The return value of that function is the `Path` to the compile jar.

== Run Rocket Chip Generator

You can run the generator with the Wake rule `runRocketChipGenerator`.
This function accepts a single `RocketChipGeneratorOptions` as an argument.

----
tuple RocketChipGeneratorOptions =
  global Jars:          List Path
  global TargetDir:     Path
  global TopModuleName: String
  global ConfigNames:   List String
  global ExtraSources:  List Path
  global BaseFileName:  Option String
  
global def makeRocketChipGeneratorOptions jars targetDir topModule configs =
  RocketChipGeneratorOptions jars targetDir topModule configs Nil None
----
Please see the https://github.com/sifive/wake/blob/a0d99f15cf806f917d64714934d337b392d36f26/share/doc/wake/tour/tuples.adoc[Wake tuple documentation]
for more information about Tuples.

----
wake -v 'makeRocketChipGeneratorOptions rocketchipScalaModule.scalaModuleClasspath "output".mkdir "freechips.rocketchip.system.TestHarness" ("freechips.rocketchip.system.DefaultConfig", Nil) | runRocketChipGenerator
----

== Run Simulations

The Wake rules for simulations are in the https://github.com/sifive/api-generator-sifive[API Generator SiFive] repository.

You can add it to an existing Rocket Chip workspace:

----
$ wit add-pkg git@github.com:sifive/api-generator-sifive.git
$ wit update
----

This will pull in `api-generator-sifive` as well as additional dependencies.

== Tips and Tricks

See the https://github.com/sifive/wake/tree/a0d99f15cf806f917d64714934d337b392d36f26/share/doc/wake[Wake `share/doc` directory] for documentation.
Note that this link is to a newer commit than 0.15.1 because more documentation has been written since the release.
Wake is still evolving so its hard for everything to be 100% synced, but the linked documentation should be compatible at time of writing.
