#! /usr/bin/env python

import sys
import os.path
import glob

if len(sys.argv) < 2:
  print "usage: %s <regression dir>" % sys.argv[0]
  exit(-1)

mf = open('Makefrag-torture-def', 'w')

def write(str):
  mf.write(str + '\n')

write("torture_dir = $(sim_dir)/torture")
write("regression_dir = %s" % sys.argv[1])
write("torture-tests = \\")

for test in glob.glob('%s/*.S' % sys.argv[1]):
  d = os.path.dirname(test)
  b = os.path.basename(test).split('.')[0]
  write("\t%s \\" % b)

mf.close()
